wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 3
      - 5
      - 6
      - 7
      - 8
      2:
      - 3
      - 5
      - 6
      - 7
      - 8
      3:
      - 2
      4: 3.7.9
      5: 0.10.13
      8:
      - 1
